### ISSUE TITLE
get account balances

### ISSUE THREAD

**Issue by EraticWander** [jborchma/qtrade#62]
Hi,
When I try to call get_account_balances I get the following error: AttributeError: 'Questrade' object has no attribute 'get_account_balances'

In the questrade.py file I see the function is in there, not sure why Im not able to call it. Sorry If Im missing something, im new to python.

Thanks

**Comment by jborchma** [comment]
Hey! The reason is that you probably installed the latest release, which doesn't have the new `get_account_balances`-method yet. I added it to the master branch but haven't gotten around to publishing a new release.

For now, installing via `pip install git+https://github.com/jborchma/qtrade.git@master` will install the right version as a workaround. I will hopefully get around to releasing the version on pypi this week!

**Comment by jgidda** [comment]
Thanks for the quick response!
I should have mentioned that I cloned the repository and manually installed the package today as I figured the release on pypi was not up to date. I just tried the method you mentioned above as well and am still getting the same issue.
